### ISSUE TITLE
persönliche Einstellungen des Templates 

### ISSUE THREAD

**Issue by DSP-IT** [saschaleib/dokuwiki-template-ad-hominem#1]
Sobald man in DokuWiki im Bereich "**Einstellungen fürs Template-Design"** zum ersten Mal speichert, ist die Formatierung des gesamten DokuWikis unbrauchbar. Folgende Fehlermeldung erscheint:

`a fatal error occured during compilation of the CSS file  @ini_default_fonts: .... [parse error: failed at `@ini_default_fonts: Helvetica Neue,Helvetica,Arial,sans-serif` `

Wechselt man auf ein anderes Template oder löscht die Fonts-Einträge in der Style.ini oder die gesamte Style.ini  (_dokuwiki/conf/tpl/ad-hominem/style.ini_), dann werden die Formatierungen wieder korrekt angezeigt.

![image](https://user-images.githubusercontent.com/89787719/131348014-8b7d6021-38d1-409b-9e4b-e420aa2785e9.png)

**Comment by saschaleib** [comment]
Hallo und danke für das Feedback. Ich konnte das hier in der Tat reproduzieren – es scheint aber eher ein Bug im "styling" plugin zu sein: Das Problem ist, dass es in den Listen für die Default-Fonts mehrteilige Namen gibt, die in einfache Anführungsstriche gesetzt werden. Da schreibt das 'styling'-Plugin jedesmal einen neuen backslash davor, und das macht wohl Probleme. 
Ich werde das auch an Andreas Gohr melden, der auch Autor von "Styling" ist, bis dahin empfehle ich, einfach keine Anführungsstriche in diesen Feldern zu benutzen (ich ändere das auch in den Defaults...)

**Comment by saschaleib** [comment]
Gerade getested: mit den Defaults in Version 0.3.3 tritt das Problem nicht mehr auf. Ich schließe diese 'Issue' deswegen hier jetzt, aber es bleibt noch ein Bug im 'Styling' Plugin, der noch zu beheben wäre.

**Comment by DSP-IT** [comment]
Hallo, vielen Dank für die schnelle Bearbeitung und den ausführlichen Informationen.
Wir werden Ihre Tipps so umsetzen. 👍
