### ISSUE TITLE
Ordered List Item numbering

### ISSUE THREAD

**Issue by stevedxu** [saschaleib/dokuwiki-template-ad-hominem#12]
The numbering on the ordered list is always 1,2,3..., on the first level and any level below.

This is a different behavior compare to the default dokuwiki numbering, which is 
First level: 1,2,3...
Second Level: a,b,c..
Third Level: i,ii,iii,...

Is there anyway to go back to the one that default dokuwiki template has?

**Comment by saschaleib** [comment]
I am not using nestled numbered lists, so this went a bit under the radar, I guess. Thanks for pointing it out :-)

I have added this change to the repository, it will become active with the next release (probably later this week). If you can't/don't want to wait, you can either manually update the file "content.less" in the CSS directory, or simply add the following lines to your "userstyles.css":

> `main ol ol { list-style-type: lower-alpha; }`
> `main ol ol ol { list-style-type: lower-roman; }`

Note that in the update, I also changed level four (greek lower-case letters) and five (decimals with leading zero). However, I would normally recommend to avoid ever nestling this deep (in fact, I would already advise against using the third level...)

**Comment by stevedxu** [comment]
That's a good idea and I'll try to implement it.

Thanks,
*Steve Xu*

**Comment by stevedxu** [comment]
Just a reminder. When you implement those, please also take care of print layout and make sure it will do the same. Thanks a lot.

**Comment by saschaleib** [comment]
They als work the same in Print view. However, please keep in mind that if you are using deep nestling, in particular with longer texts, you may have to fine-tune the view to your needs (either in the userstyle.css, or by adding inline-styles.

In particular in the two-column layout, which is only available on browsers that supports columns in print view (Firefox, mostly) as the lines can get rather short in this situations.

You may want to reduce the font size, at least in deeper nestling levels, if space gets tight. Or disable the two-columns layout in the userstyles.css (e.g. by "#main-content { columns: 1; }

**Comment by stevedxu** [comment]
Great thanks for the tip.

**Comment by saschaleib** [comment]
Fixed in 0.5.3, published on 05.01.2022.
