### ISSUE TITLE
TOC is not showing on PC browser

### ISSUE THREAD

**Issue by stevedxu** [saschaleib/dokuwiki-template-ad-hominem#13]
When I defined header level inside the content and setup the TOC, it is showing correctly on my mobile phone with the drop down menu that I can expand and collapse. However, on PC, it is a different story. I tried several different browsers and that icon is dead, not functioning at all.

**Comment by saschaleib** [comment]
Again, could you give some more information, like which browser, how many headlines you have, window size, etc. Best would be a link where I could test it directly...

**Comment by stevedxu** [comment]
I tried it on FireFox, Chrome, Edge, all the same. As long as it is on PC, it doesn't work even if I shrink the window width to the smallest. It only works on my mobile phone browser, which is an Android browser. I tried several and all works fine.

Here is my website. However, since it is in Chinese. I doubt you can read it. But you can see how it is not working. The TOC icon at the top right corner is showing but not clickable.

https://stemofjesse.org/doku/doku.php/%E6%99%A8%E5%85%B4%E5%9C%A3%E8%A8%80:2017:2017.04.%E5%A4%8F%E5%AD%A3%E8%AE%AD%E7%BB%83:%E7%AC%AC%E4%BA%94%E5%91%A8

**Comment by saschaleib** [comment]
I had a look at the JS code on your site. On a first glance, it seems there is some other plugin interfering with the clicks on the TOC. Could you try:
First, disable any plugin may interfere with the HTML code and try if that changes the situation.
If that doesn't help, uncheck the "compress" option in the site options (section "Advanced"), just so I can debug the site more easily...

**Comment by stevedxu** [comment]
I just disabled gzip compress option. I do have many plugins which contribute to the page formatting/rendering. Not sure which one to disable though. The only thing I can say is that this works well with the original dokuwiki template. So sorry if my other plugins are causing issue for yours.

**Comment by stevedxu** [comment]
I also cleared all cache hopefully that would generate a new fresh rendering of HTML code.

**Comment by stevedxu** [comment]
By looking at the page source, it shows as below. Please note the class on id toc, it says "toggle hide"

```
<header>
<aside id="toc" class="toggle hide">
<h3 class="tg_button" title="Table of Contents"><span>Table of Contents</span></h3>
<div class="tg_content">
<ol>
<li>
```

**Comment by saschaleib** [comment]
Hi again, it looks to me as if you disabled "gzip_output", not "compress". The "GZIP" compresses all output for the transfer throught he internet (makes the pages load faster), whilc "compress" removes all extra spaces and newlines and comments from the JS and CSS files, which also makes the page load faster, but also makes it very hard to debug the code :-) 

What I can see already is that for some reason the JS event that should be triggered when the user clicks on the H3 button is not assigned to this element. I could not find out why that happens, though.
Unless we can figure out what is happening here, you can also add a temporary fix to always show the TOC by adding the following to your userstyle.css:

`#toc.hide h3 > span, .toggle.hide .tg_content {
    display: block;
}`

**Comment by stevedxu** [comment]
Thank you. It turns out to be some cloudflare settings which cause this issue. I'm testing all different combinations to see what works the best. Thank you so much for your effort.

**Comment by saschaleib** [comment]
Thanks, my pleasure and have fun with your site! :-)

**Comment by stevedxu** [comment]
The setting is the Cloudflare Rocket Loader™ which is causing issue. I have turned off that and had all the other optimizations still on and it works perfectly fine. Thanks a lot and if I haven't say so, I like your template very much and that's why I really want to make it work with my site. Great job!

**Comment by saschaleib** [comment]
Thanks, I feel patted on the sholder :-)
