### ISSUE TITLE
I installed this and corrupted Doku somehow

### ISSUE THREAD

**Issue by braynebuddy** [saschaleib/dokuwiki-template-ad-hominem#17]
I'm just starting to try to fix this anf get my wiki back. Here's what I get from the main page...
`Fatal error: Uncaught ArgumentCountError: Too few arguments to function dokuwiki\StyleUtils::cssStyleini(), 0 passed in /homepages/19/d262839999/htdocs/clickandbuilds/dokuWiki/Notebook/lib/tpl/ad-hominem/my_template.php on line 84 and at least 1 expected in /homepages/19/d262839999/htdocs/clickandbuilds/dokuWiki/Notebook/inc/StyleUtils.php:19 Stack trace: #0 /homepages/19/d262839999/htdocs/clickandbuilds/dokuWiki/Notebook/lib/tpl/ad-hominem/my_template.php(84): dokuwiki\StyleUtils->cssStyleini() #1 /homepages/19/d262839999/htdocs/clickandbuilds/dokuWiki/Notebook/lib/tpl/ad-hominem/main.php(27): my_metaheaders() #2 /homepages/19/d262839999/htdocs/clickandbuilds/dokuWiki/Notebook/inc/actions.php(27): include('/homepages/19/d...') #3 /homepages/19/d262839999/htdocs/clickandbuilds/dokuWiki/Notebook/doku.php(120): act_dispatch() #4 {main} thrown in /homepages/19/d262839999/htdocs/clickandbuilds/dokuWiki/Notebook/inc/StyleUtils.php on line 19`

**Comment by saschaleib** [comment]
Hello and thanks for the feedback :-) On first glance, this looks more like there is something wrong with your styles configuration.

To make sure this is related to this template, could you please check if this does not occur when the default template is active? You may have to manually edit conf/local.php to change the template in case the DokuWiki instance is not running...

Secondly, please see if there is a custom style set in conf/tpl/ad_hominem/style.ini and if so, delete or rename it.

My hunch is that there is something wrong either in this, or in your conf/userstyle.css file... also try deleting/renaming this one.

If none of these help, please send more information about your environment: which DokuWiki version, which Template version and also which PHP version are you using?

**Comment by braynebuddy** [comment]
As soon as this happened I figured it was something wrong with my configuration. Your response was VERY helpful in pointing me to the conf/local.php file. I changed back to the default template and was able to get DokuWiki running again. 

When I did that, I checked the version and found, "Release 2018-04-22b "Greebo"". Your site clearly says this is NOT on the supported list of versions! I am running on PHP Version 8.0.20.

I couldn't find conf/tpl/ad_hominem/style.ini, in fact there is no conf/tpl directory. Same thing with the conf/userstyle.css file, it doesn't exist. I suspect this is related to the DokuWiki version.

In any case, thank you for your quick response!

**Comment by saschaleib** [comment]
Glad I could help ... but even glader it isn't a bug in my template after all :-D

I should probably add that "Greebo" is no longer receiving updates and shouldn't be used any longer; Also PHP 8 support is only planned for the next DokuWiki version, so that might be another cause of problems for you. In any case, I would recommend to upgrade DokuWiki to Hogfather, and downgrade PHP to 7.x for best results.

But whatever you do, make sure you have fun! :-) Best greetings

**Comment by saschaleib** [comment]
Closed because not in scope.
