### ISSUE TITLE
Error in struct plugin (igor, PHP8)

### ISSUE THREAD

**Issue by Dob4115** [saschaleib/dokuwiki-template-ad-hominem#18]
An error pops up on "random" pages, usually going away after a refresh: `Warning: Trying to access array offset on value of type null in /volume1/web/dokuwiki/lib/plugins/structsection/syntax.php on line 89`

This led me to discover that there  is a persistent error in the struct plugin's table of contents (have to expand it). Each entry says: `Warning: Undefined array key "hid" in /volume1/web/dokuwiki/lib/tpl/ad-hominem/my_template.php on line 465`

**Comment by saschaleib** [comment]
Hi @Dob4115, thanks for pointing this out. I'm still reluctant to use PHP8 on my site, because a lot of DokuWiki AddOns have such problems; But I will investigate where this comes from and try to make sure at least my template isn't one of the "showstoppers" :-)

**Comment by saschaleib** [comment]
I just released a new version 1.3 (with date: 04/11/2022) that should resolve this issue. Please let me know if you still have any problems...

**Comment by saschaleib** [comment]
OK, I found a similar issue in the same place, this time only affecting PHP 8.1... Expect 1.3.1 soon ;-)

**Comment by Dob4115** [comment]
Updated by copying over the old template and confirm that the struct's TOC works correctly now. Thanks!
