### ISSUE TITLE
Github Repository Sym Links

### ISSUE THREAD

**Issue by felix-ulonska** [saschaleib/dokuwiki-template-ad-hominem#2]
This Github Repository uses a lot of sym links. Is there a reason for that? Sadly I cannot clone the project because of that

**Comment by saschaleib** [comment]
Hi there, indeed, I wasn't aware of that. At first glance, that seems to be a quirk of my client (SmartGit). I'll see if I can find a workaround.

**Comment by saschaleib** [comment]
This seems to have been a quirk of the Git client I was using. I have now moved to the GitHub client, and that should resolve this issue in the next update.

**Comment by saschaleib** [comment]
It was more complicated than that :-) In any case, the symlinks are now gone, hooray!
