### ISSUE TITLE
Edit Page, Edit Summary Textbox does not resize on small screen resolutions

### ISSUE THREAD

**Issue by Dob4115** [saschaleib/dokuwiki-template-ad-hominem#24]
Working on Dokuwiki on my phone (sigh), the edit summary textbox sticks out past the side of the page. When I click into it, the page shifts and I can no longer tap the save/preview buttons. 

Is the textbar width controlled by the template? Does/should it respect page width?

**Comment by saschaleib** [comment]
Hi there, could you send me some more information about your setup? Especially which browser and which screen size you are using. I have tried in both in Safari and Firefox on iOS (iPhone XR) and could not replicate the problem, but I can try some other browsers to try and find the issue, of course... Best greetings /s.

**Comment by Dob4115** [comment]
I'm using the latest version of Vivaldi on a Pixel 4a running Android 13. I'm in portrait mode... not sure how to tell screensize?

**Comment by saschaleib** [comment]
Google Pixel 4a has 1080 x 2340 pixels at 443ppi. That's all the info I need :-) I'll investigate this when I'm back home (I am travelling at the moment).

**Comment by saschaleib** [comment]
Hello again. I tried to replicate this issue, even installed Vivaldi for Windows to see if it is replicable there, but can't seem to replicated it.

However, in the process I noticed that the login form sticks out of the screen on small screen sizes, so I fixed that instead :-) 

Could you post a screenshot of how it looks like for you, maybe I can get more hints out of that. Also, do you have any other plugins installed that might affect this element?

**Comment by saschaleib** [comment]
While I still could not replicate the specific issue, I have made some changes to the edit elements, which probably fixes such issues as well. Please have a look if you still encounter this problem with the new version :-)

**Comment by Dob4115** [comment]
Nice. Putting them on separate lines works really well. Solves my problem!

**Comment by saschaleib** [comment]
Excellent. Another job well done ;-)

**Comment by saschaleib** [comment]
Excellent. Another job well done ;-)
