### ISSUE TITLE
Wide pages truncated when sidebar is shown

### ISSUE THREAD

**Issue by suedunham** [saschaleib/dokuwiki-template-ad-hominem#25]
New glitch with the new version, possibly connected to the horizontally-scrolling `pre` blocks. It seems like the overall page width is set with reference to that of the main panel when that is all that is shown. In other words, when the show/hide sidebar button is toggled to hide it, everything seems to be in the right place.

However, when that toggle is set to show the sidebar, that main panel does not resize. Furthermore, no horizontal scrollbar appears in the browser window, so text at the right edge is no longer visible.

As an example, that PHP code block [from here](https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/21#issuecomment-1383168779) will show the problem.

**Comment by saschaleib** [comment]
This one was definitely harder than I though. The solution I found now seems to work, but is definitely not perfect. So, something to re-visit at a later point, I guess...

**Comment by saschaleib** [comment]
Fix is rolled out in 1.4.1.
