### ISSUE TITLE
Page editor: darkmode buttons in lightmode

### ISSUE THREAD

**Issue by suedunham** [saschaleib/dokuwiki-template-ad-hominem#26]
Some elements of the page editor seem to be rendered for darkmode even when the lightmode is engaged.

![ad-hominum_dark_buttons](https://user-images.githubusercontent.com/42522840/212970215-257fe659-81fa-4f80-9b9c-b2f254aa2be9.jpg)

**Comment by saschaleib** [comment]
Indeed, that was an oversight here. Will be fixed with the next update...

**Comment by saschaleib** [comment]
This is now fixed in 1.4.1.
