### ISSUE TITLE
Search Dropdown Doesn't Populate With Small Screen Widths

### ISSUE THREAD

**Issue by Dob4115** [saschaleib/dokuwiki-template-ad-hominem#28]
Again, not sure if this is a template issue or not. Again, using Vivadi on Android (and it happens on Desktop), if the screen width is "too small" (I dont know the specific size, desktop Vivaldi allows you to tile tabs vertically... 4 vertical tiles causes the problem) the contents of the search dropdown are not displayed. The dropdown appears, but isn't populated (it's just a thin, horizontal sliver).

**Comment by saschaleib** [comment]
Hello and sorry for the late replay (busy here these days ;-)

Could you please post a screenshot so I can see how it looks like? I am trying this in Vivaldi Desktop with the Developer Tools to shrink the view to a small enough size, but the result is pretty much how I expected it (see below).

![image](https://user-images.githubusercontent.com/961863/216818102-3a9e923f-4bea-4ff1-865d-280a016c6f02.png)

**Comment by Dob4115** [comment]
![Screenshot_20230205-074008](https://user-images.githubusercontent.com/49409988/216819208-6d847add-31ce-451b-a041-2b7a5fb533a1.png)

This is full width. Though, in getting that screenshot, I realized that the error is much more random than I thought. I noticed that when it displays the menu correctly, I'm able to zoom.

**Comment by Dob4115** [comment]
Here's a shot after zooming it, during failure:
![Screenshot_20230205-081438](https://user-images.githubusercontent.com/49409988/216821102-397e5fac-1f74-4c1a-9cf3-c2a14dfb0cb1.png)

**Comment by Dob4115** [comment]
I installed 1.4.2 and I still have the same problem. If I make the screen wide enough, it works.

**Comment by Dob4115** [comment]
Oh, wait... I reset the browser cache and it seems to be working better. I'll test it over the next day or so and get back to you. Thanks!

**Comment by Dob4115** [comment]
Well... it works if I type in the wiki search bar on the search page. If I type in a normal page's search bar, it doesn't work.

**Comment by Dob4115** [comment]
I'll keep testing to see if I can repeat success/failure. Pages I've visited recently dont work, but pages I havent been to for a long do work. That sounds like a "cache-like" issue.

**Comment by saschaleib** [comment]
Indeed, that sounds like the old CSS is still cached in the browsers.

**Comment by saschaleib** [comment]
For comparison, this is how it looks in my tester now:
![image](https://user-images.githubusercontent.com/961863/220768919-e912c6cf-8a6d-40fb-b15a-feb02116db98.png)
The second result is an extra long page title that previously broke the search popup. I can only assume that there was something similar happening in your browser...

**Comment by Dob4115** [comment]
I'm marking this closed. I have yet to see the empty search results in the last day. Thanks!!

**Comment by saschaleib** [comment]
Thanks for the update. I still have one more very minor touchup to do here, but that can come with the next update. I am working on the print styles now, so a new version should come rather soon... Cheers :-) /sascha

**Comment by Dob4115** [comment]
I think this issue should be reopened. Often, an initial visit to a page still yields an unpopulated search dropdown. If I refresh the page (F5), the dropdown works as expected. Is there something different about the initial visit that doesn't set the screen width stuff correctly?

**Comment by saschaleib** [comment]
Reopening is a good way - but I still have problems replicating this behaviour. It is still on my watchlist, though...

**Comment by Dob4115** [comment]
Ok, I think I have some more information. I've been getting some php-related errors (from structsections plugin). When I inititally go a page in the wiki, the error shows and search dropdown does not populate. When I refresh, the error goes away and the search dropdown works fine. 
Today, I tried setting hidewarnings and things are working fine: no errors displayed and search dropdown works all the time.
So is there something about encountering errors that changes the way the search dropdown populates?

**Comment by saschaleib** [comment]
These PHP errors are an absolute pain, but luckily DokuWiki now offers a way to redirect them to a log file. If there are no further problems, I will just close this for now...

**Comment by Dob4115** [comment]
Yeah, I haven't noticed any problems recently. Still using this template. Thanks for the hard work!
