### ISSUE TITLE
Add Current Page Breadcrumb For Admin Actions

### ISSUE THREAD

**Issue by Dob4115** [saschaleib/dokuwiki-template-ad-hominem#3]
Love this template! 

My problem is that the current page breadcrumb is not visible. In normal wiki pages, this is not a problem, but when you go to admin pages and then want to return to the "base" page, you have to use the back button (sometimes multiple times). Is there a way to enable the current page breadcrumb only when in admin pages?

**Comment by saschaleib** [comment]
This one is a bit difficult, as I removed this on purpose - I feel that the breadcrumb should not repeat the title of a page that is already stated just underneath.

Even if I would add the page title, I would not make it a link, as a link that only leads back to the same page is clearly superfluous. I'm all for removing noise from a page, in the interest of keeping it clear and comprehensible for the user...

Having said that, I also sometimes find myself in the situation where I would like to go back to the page while editing (or opening the same page in a new tab, so I can compare what was there before).

So far, my argument (against myself) was always that what makes the experience better for the user, may well add a small inconvenience to the editor. At least *I* was convinced by that argument so far :-) 

Unfortunately, there is no easy way to make this link visible only in admin or edit mode. But I'll look into that, as this may also be interesting for some other features.

PS: Glad you like the template. Just wait the next version adds a system-controlled "dark mode", i.e. if the user has the operating system set to "dark mode", the web site follows that setting. I was never a fan of dark mode, but I think it looks great! :-)

**Comment by Dob4115** [comment]
Yeah, I agree with removing the breadcrumb from all pages... except admin! But understand that that might be impossible. Not a huge deal, I suppose.

Yes, this is the best template I've seen as an alternative to the default... definitely shows attention to detail!

**Comment by saschaleib** [comment]
Thanks, I feel patted on the shoulders :-) Also I definitely see your point, and even if I don't have a solution for this yet, I'll keep this issue open, just in case I can still find a good solution some day.

**Comment by saschaleib** [comment]
This is now possible in version 0.4.5 (2021-12-10) – it is implemented as a configuration option to show the current page in the breadcrumbs either as text or as link. Default is "don't show", though.

**Comment by Dob4115** [comment]
Really like the option. Just one very minor request: I set it to show the breadcrumb as text, but it shows the full path in the last breadcrumb. Could you just show the page name (not the namespaces) for the text? 

If not, no complaints here!

**Comment by saschaleib** [comment]
Hi again, could you post a screenshot how it looks for you? For me it is like this (in dark mode): 
![image](https://user-images.githubusercontent.com/961863/145682215-62eb8d4b-b860-4bdc-8214-969820e8759b.png)

**Comment by Dob4115** [comment]
Sure:

![image](https://user-images.githubusercontent.com/49409988/145683285-515ee5fe-566e-4e94-8fb5-0e8077c127d4.png)

**Comment by saschaleib** [comment]
Yeah, that looks definitely like a bug. Let me see if I can replicate this...

**Comment by saschaleib** [comment]
Could you just check how the setting "Use first heading for pagenames" ([useheading](https://www.dokuwiki.org/config:useheading)) is configured for you? If this is "never", then indeed that is how the page name is shown by DokuWiki. It should be either "Navigation only", or "Always" to show the first heading name in this place. This is how it looks with "never" (the default) here:
![image](https://user-images.githubusercontent.com/961863/145683957-98987ed5-b635-4ec3-8e79-eeab7e139c04.png)
Note also that the page header (in the browser title bar) is shown like this in this case.

**Comment by Dob4115** [comment]
Interesting. Mine is set to Wiki Content Only. I'll try setting it to always.

**Comment by saschaleib** [comment]
I will leave this open, even though I consider this a bug in the DokuWiki core; But it is one that I might be able to work around in the template - just that I don't think this should be a priority... and with some luck it will be fixed in DokuWiki before I manage to find some time for this ;-)

**Comment by Dob4115** [comment]
Nice. I havent upgraded yet, but nice to know.
