### ISSUE TITLE
Dark mode code blocks have light scrollbar

### ISSUE THREAD

**Issue by suedunham** [saschaleib/dokuwiki-template-ad-hominem#32]
I appreciate your work on code blocks, like [in this issue](https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/25), but I have one quibble yet. In dark mode, the horizontal scrollbar given to wide code like that handy `doku.php` example looks like a light theme one.

Other than that, they're working much better. Thank you.

**Comment by saschaleib** [comment]
Hello again:-) This is actually a good idea to improve, and easy to do as well. I have just committed a few changes to the styles to make sure the scrollbars look better (bot in light and in dark mode). I'll still do a bit more testing, but this should be rolled out with the next minor release.

**Comment by saschaleib** [comment]
Resolved in 1.5.1.
