### ISSUE TITLE
TOC levels are misaligned

### ISSUE THREAD

**Issue by popescu-tibi** [saschaleib/dokuwiki-template-ad-hominem#36]
Hello!

I noticed that the table of contents of the ad-hominem template is not aligning properly the subtitle levels when there is more then one level difference between them.

This is how the table on contents looks when using the default dokuwiki template:

![dokuwiki-toc](https://user-images.githubusercontent.com/63455791/230623165-4ef9bbd6-3601-4e1b-b441-393a5fac743b.png)

This is how the table on contents looks when using the ad-hominem template:

![ad-hominem_toc](https://user-images.githubusercontent.com/63455791/230623240-d4db05eb-0155-4706-8df8-da9dc105c55f.png)

This is the wiki code:

```====== Title 1 ======
===== Title 2 =====
==== Title 3 ====
=== Title 4 ===
===== Title 2 =====
==== Title 3 ====
```

The second Title 2 should be aligned with the first one which is also a level 2 title but instead it's aligned with Title 3 (level 3 title). This seems to happen only between titles of levels which are not consecutive. For example if I insert a level 3 title between  `=== Title 4 ===` and `===== Title 2 =====` is behaves as expected.

**Comment by saschaleib** [comment]
Thanks, this is indeed an interesting issue. I'll have a look at it :-)

**Comment by saschaleib** [comment]
This should now be fixed in the latest version, along with some other issues with the TOC.
