### ISSUE TITLE
Syntax Blocks are falling behind.... something? Help! :)

### ISSUE THREAD

**Issue by eightysixed** [saschaleib/dokuwiki-template-ad-hominem#37]
Hello!
Something weird is happening now that I've upgraded to [Jack Jackrum](https://www.dokuwiki.org/changes), I thought it was because Dokuwiki stripped out HTML and PHP embedding in this new version.

But, all `<code>` blocks fall behind something, as does the official `wiki:syntax` page, I've attached a screenshot of what's going on to this post. I'm using the latest version of _Ad Hominem (Last updated on
2023-04-20)_

If I revert to the "default" Dokuwiki template it all works fine...

How can I fix this, as it's a pretty big problem? Thank you! :)

**edit:** I had a hunch that if I turned off _Dark Mode_ it might actually work. I was wrong. So let's rule that out :)

**edit2:** I also tried in different browsers with brand new cache. I can't seem to figure out what's going on. Thanks for the help! :)

Screenshot attached! Thanks again! :) 

![9E75CD33-53A6-4398-A1F9-07269C1F11B2](https://user-images.githubusercontent.com/1641513/233763535-b79632ed-9b2f-4fc1-bed7-03de4dcc2a90.jpeg)

**Comment by saschaleib** [comment]
Hello, this is indeed weird. I have tested it on several of my own sites and the Syntax page looks fine for me. My hunch here is rather that some other plugin is interfering with the styles here. If it is a public site, could you send me a link (by email, if you prefer not to disclose it) so I can check what is up there?

**Comment by eightysixed** [comment]
Good morning! Thank you for the quick reply. Using ACL Management, I've opened up `wiki:syntax` and it can be found [here.](https://wiki.kevinclark.me/wiki:syntax)

It really is the strangest thing. I guess I could start disabling plugins one by one, but if you can easily see the problem outright, that would also be helpful! :)

Thanks for looking into this for me! :)

**Comment by saschaleib** [comment]
OK, I found something interesting: firstly, it is indeed related to the template, and it refers to this line of CSS code:
`max-width: calc(@ini_site_width - @ini_sidebar_width - .5em);`

Apparently, in your case, this calculates as:
`max-width: calc(-100.5%);`

… which of course causes the element to collapse to the smallest possible value (zero + padding) and this is what you see there...

Now, I'm a bit puzzled how this can happen. Just to be sure, could you check what settings you have in the "Template Style Setting" for these values here:
![image](https://user-images.githubusercontent.com/961863/233794038-c3c1d05f-9d5b-423c-ba0e-7cc70c44369b.png)

These are actually the "site_width" and "sidebar_width" parameters, and if there is something weird in the latter, that would explain the result.

Alternatively, you could just add something like the following to your `userstyle.css` file:
`main pre { max-width: 100% !important; }`

I will still look into the CSS in my template to see if that calculation is actually necessary... but let's first check your Template Style settings....

**Comment by eightysixed** [comment]
Hello!
Thanks again for a timely and informative and helpful reply!

Below is a screenshot of my template settings. Thanks again, I'm sure we'll get this fixed :)
Hopefully it's something that I've done and you don't have to push out changes or anything :)

![48796C8E-2EC4-45CF-85AC-64A88A18666D_4_5005_c](https://user-images.githubusercontent.com/1641513/233795223-a10cbb64-d386-4eb2-84de-7554104f7b20.jpeg)

**Comment by saschaleib** [comment]
Indeed, I could replicate the problem now if I also change the site width to 100% (which is generally a bad idea – your users may have a screen [like this one](https://www.samsung.com/de/monitors/gaming/odyssey-neo-g9-g95na-49-inch-ls49ag954npxen/) and then your text will run over the whole width).

However, I think there is a different underlying problem. It seems that the width is calculated by just using the numbers (100 - 200 - 5) and the measurement units are ignored. This may be a bug in how LESS works. I'll investigate this.

But for now, my recommendation is to use a fixed width for the site (it will always only work as a "maximum width", so you can set it relatively high, if you really want that ultra-wide view).

**Comment by saschaleib** [comment]
Please try to update the template. This should (!) be fixed now with the latest version.

**Comment by eightysixed** [comment]
Oh dear, sorry for all the trouble but at least I found a bug, albeit not one many could uncover. Thanks for your quickness in helping me (and maybe others) with this.

With that being said, there's no `Update` button under `Extension Manager -> Installed Templates` like there normally is. Do I have to manually upgrade?

**Comment by saschaleib** [comment]
I also noticed that in some cases it takes a while for the DokuWiki Extension Manager to realize that there is a new version available.

Like, yesterday after the release I updated all my wikis, and in about half of them there was no update button yet. It is there now, though...

In urgent cases, you can always do a manual update (see my other answer here) but most of the time it is enough to try again in an hour or two.

**Comment by saschaleib** [comment]
So here we go again. Turns out, tissue is still not fixed "head and tail" in today's release. There will be another release to finally be done with it (I hope! ;-)

**Comment by eightysixed** [comment]
Hello!
So wait, what happened? I just updated at 3:03pm UTC-5 and everything went back to normal? What happened?

**Comment by saschaleib** [comment]
Yeah, I noticed that now the pre tag looks weird under some other circumstances... 

The problem with this tag is that it is used by DokuWiki for the `<code>` blocks as well (instead of actual `<code>`) and because of the way this works, it is a bit complicated...

So if it works for you now, then no worries. If someone reads this because their code blocks worked before and now not... sorry ... will work again tomorrow :-/

**Comment by eightysixed** [comment]
Oh no!

I'm sorry for opening up such a **huge** can of worms. I guess it's a learning experience for all of us, I suppose.

Thank you so very much for taking the time and effort to dive into this and take it head on. Others will most certainly learn from it. 

Please keep this issue Open and let us/me know how everything turns out!

Thank you again! :)

(sorry :) )

**Comment by saschaleib** [comment]
No need to feel sorry. This is like solving Sudokus for me :-)

**Comment by eightysixed** [comment]
I love Sudoku 🙂
So where do we stand today?

**Comment by saschaleib** [comment]
Today's version should be fine :-) Until the next bug, that is ;-)

**Comment by eightysixed** [comment]
Okay, fair enough. I was just curious because the last commit I see in GitHub is [this.](https://github.com/saschaleib/dokuwiki-template-ad-hominem/commit/c26ddac78b042ce86d579103d497ed42d3a5edc8) Which only a date update :)

**Comment by eightysixed** [comment]
More specifically was curious about this:

> So if it works for you now, then no worries. If someone reads this because their code blocks worked before and now not... sorry ... will work again tomorrow :-/

**Comment by saschaleib** [comment]
But before that were some CSS updates. I always do the info file update last (and sometimes forget it ;-)

If you have the version from 24.04 on your wiki, that is the latest one and I hope that fixes now all the issues. Was an interesting case in fact. But it would have been easier if DokuWiki actually used `<code>` for embedded code and not `<pre>`, even though you enter code tags in the source code... and then others want to use pre for other purposes and then things get all pear-shaped... oh well. 

In any case, let me know if it works for you, so I can close this issue... :-)

**Comment by saschaleib** [comment]
Yeah, I found that the fix that solved the issue for you may open another issue that only occurs under other circumstances. As I said, `<pre>`is complicated... That's why I had to make another quick update.

**Comment by eightysixed** [comment]
Nope, I'm good to go! Again, thank you very much for investigating all of this, figuring it out, and implementing a fix! 
I appreciate it very much.
Did you figure out if LESS is supposed to behave I that manner?

Remember, MORE is LESS, more or less ;)

**Comment by saschaleib** [comment]
At least I can say I wasn't the first one to fall into the trap with how LESS calculates values, so there was a lot of documentation on the Internet :-) Also, it seems that they fixed this in later versions, but this isn't implemented in DokuWiki yet...

In any case, you are welcome, glad I could help (and improve the template :-)

Let me also reiterate that a value of `100%` for the page width can have some bad side-effects in terms of user-friendliness. I would recommend to always set a fixed maximum width. This can be wider than your own screen, if you really want to have such large pages, but limit it somewhere; Screens are getting bigger and bigger and a very long measure (=length of a line) is very hard to read... just for reference: I sometimes combine 2 x 4K monitors into one for some application (MS Flight Simulator, mostly) and that gives an even wider monitor than the one I linked above. Text that spans two such monitors is definitely way out of scale in terms of readability..

Well, it is your site after all... ;-)

In any case, I'll close this now. Don't hesitate to open another one if you find some problems. All the best :-)

/sascha

**Comment by eightysixed** [comment]
The only reason I chose to pick `100% page-width` is because the template is responsive, and the template scales as such.

Those of us with these huge monitors, generally keep multiple panes/windows open at the same time, visible on the monitor all at the same time.

So I/we can shape the browser to each user's preference, and the DokuWiki template scales as such. I might be missing something on this, but it seems incredibly convenient.

**Comment by eightysixed** [comment]
That is to say, it's 100% of the window/pane, not 100% of the screen, unless you have everything full screen in a dev environment, which would seem strange in and of itself.

**Comment by saschaleib** [comment]
Well, it is your site and your decision, so I leave it with this. In any case, have a good time :-)

**Comment by eightysixed** [comment]
Thank you so very much for your time and effort. Sorry I was a headache :)
Be well, friend.

**Comment by saschaleib** [comment]
No headaches at all :-) Have a good time! :-)
