### ISSUE TITLE
Trouble updating, old template.info.txt

### ISSUE THREAD

**Issue by suedunham** [saschaleib/dokuwiki-template-ad-hominem#38]
Even though, when viewed here, the `template.info.txt` is dated 2023-04-22, the one I've downloaded through the extension manager and again from here reads 2023-04-20.

**Comment by eightysixed** [comment]
Oh dear, I've accidentally created a monster :(
Sorry guys :(
Sascha will figure it out! :)

**Comment by saschaleib** [comment]
Indeed, my bad. I committed the change, but then forgot to push. I'll make another release in a few moments, hopefully with the correct date in the info file.

In the meantime, you can also update by copying the download link into Manual Install -> URL field. Don't forget to check "Overwrite existing files".

Please use the opportunity to admire the new design of this tab (I am using this method a lot during development, so I really wanted this to look a bit better than the original ;-)

**Comment by saschaleib** [comment]
Fixed in today's release. It might still take a few hours to see the new version announced in the Extension Manager (in my tests: it worked in one out of 4 wikis immediately, one more within an hour)...
