### ISSUE TITLE
Bug in how Footnotes work on mobile devices

### ISSUE THREAD

**Issue by eightysixed** [saschaleib/dokuwiki-template-ad-hominem#42]
I've came across this, and it's a bit weird. I can replicate this no matter what, no matter where and so can others.
It should be a pretty easy fix (hopefully).

I've opened up my Playground so you can see the replication.

When a footnote has a link in it, it works as usual on a desktop/laptop/Mac/PC and shows the little 'tooltip' type of box (for a lack of a better term). It also does if it's just a "nothing but text" footnote.

However, on mobile devices the Footnotes that contain a link behave as normal, but the one(s) that do not and only display text either immediately vanish or jump you down to the Footnote Reference.

I've only tested this on an iPhone, and my users as well. What do you think? 

Look at the difference between the first footnote (containing a link) and the second one (which is text-only), and compare them on a phone/mobile device versus a regular laptop/desktop, you'll see what I'm talking about.

Is there a way to correct this?

Playground link below.

[Playground Link!](https://wiki.kevinclark.me/playground:playground)

**Comment by saschaleib** [comment]
That is indeed interesting - and I can replicate it in my dev environment. I'll have a closer look at this...

**Comment by saschaleib** [comment]
OK, so after some testing: the same problem also occurs under the default template, meaning it is an issue in DokuWiki.

However, I never tested the footnotes with the template - well, I'm not really using them - and found a few things that I could improve, including a better formatting, dark mode support and nicer printing as well. So it was definitely worth a bit of digging in.

Oh, and on my (older) Android phone, the footnote popups don't work at all. So there are definitely some issues to be resolved here...

Anyways, closing this here now as it is not within the scope of the template.

**Comment by eightysixed** [comment]
Hello again, and thank you for diving into something else. (Sorry if I'm a thorn in your side, finding all of these things :-)

With that being said, since we've identified it as a core DokuWiki problem, where is the proper place to open the issue? Their Git? The forums? Or did you already do it? 

I only ask because I'd sort of like for this to be fixed :)

**Comment by saschaleib** [comment]
In principle it is the DokuWiki repository ... but I would first go to the [DokuWiki Forum](https://forum.dokuwiki.org/)...

**Comment by eightysixed** [comment]
Sounds good, will do! 

Thanks again! :)

**Comment by eightysixed** [comment]
Wow, yes, that does look a lot better in the dark theme! Thank you!

I'll try to bring this issue to the Forum later today or tomorrow (and probably might as well open an issue here on Github, too. Couldn't hurt :-)
