### ISSUE TITLE
Updated AH, broke my plugins

### ISSUE THREAD

**Issue by Elfinlocks** [saschaleib/dokuwiki-template-ad-hominem#45]
I absentmindedly updated AH to the latest version and now my plugins are all broken and formatting horribly (notably Wrap and EditTable) - is there any easy way to determine what version I was on and to revert the changes? This has kind of screwed up all of my pages.

**Comment by Elfinlocks** [comment]
For future readers, I fixed this by locating the old version of AH by determining which initial one I installed through my DokuWiki logs, and then installed the old template manually to dokuwiki/lib/tpl/ad-hominem, and make sure you also copy style.ini to dokuwiki/conf/tpl/ad-hominem as well.

**Comment by saschaleib** [comment]
Hello and thanks for raising this .. glad you found the link to the previous versions ... but of course, the template should work with all common plugins, so if there is a problem, let me have a look if I can fix it :-)

Could you post more information on the issues you encountered? If you have a test page where I can see the problem it would be of course ideal ...

**Comment by Elfinlocks** [comment]
Sure thing - here's the rundown on what occurred:

Old AH version (where things work): 2023-04-01
[Wrap version](https://www.dokuwiki.org/plugin:wrap): 2022-08-10
[EditTable version](https://www.dokuwiki.org/plugin:edittable): 2023-01-14

New AH version: 2023-05-04

With the old version, my Wrap boxes and table editor look as such:
![image](https://github.com/saschaleib/dokuwiki-template-ad-hominem/assets/43624750/c0ecd72e-1e66-4dff-98e9-2285a11f8874)

![image](https://github.com/saschaleib/dokuwiki-template-ad-hominem/assets/43624750/bc609632-5205-4f37-bd41-4ff226f54048)

However, when you install to the newer version of AH, it looks like this with 0 changes to the page itself - first, the wrap boxes "bleed" together like this:

![image](https://github.com/saschaleib/dokuwiki-template-ad-hominem/assets/43624750/e68dff3d-9d08-4b97-92e5-0c8c3d66c6d4)

And the table editor becomes strangely scaled and difficult to read:

![image](https://github.com/saschaleib/dokuwiki-template-ad-hominem/assets/43624750/e3fd3b7b-3e74-4b97-8b7c-6590f9393546)

I would have normally chalked this up to some kind of disagreement between the editor and the actual text on the page, but it seems to occur in the table editor as well.

**Comment by saschaleib** [comment]
OK, so the short answer is: if your plugins don't support dark mode, you can either:

1. Report this as a bug to the plugin author(s) (and hope they fix it)
2. Find the plugin repository on GitHub, and try to supply changes yourself,
3. Add custom CSS (e.g. in `userstyle.css`) to provide the missing colours for the plugin
4. Not enable dark mode for your site.

While I can add specific CSS for common plugins to make them compatible, it is not possible to provide that for all the thousands of plugins that are available for DokuWiki. Some of them will just not work with dark mode, or with any other feature or design decision of this template.
