### ISSUE TITLE
Is it possible to always show the TOC?

### ISSUE THREAD

**Issue by windowsrefund** [saschaleib/dokuwiki-template-ad-hominem#47]
Absolutely love this template! My TOC is always collapsed though and I'd love to set it to always be shown.

Thanks in advance.

**Comment by saschaleib** [comment]
Hello there, my idea was the the TOC can get quite in the way and in most cases, articles are best read from top to bottom, so the TOC is best kept "out of the way" unless really needed.

But as a workaround, you could add something like the following into your custom CSS files (e.g. `userall.css`).

```
.toggle.hide .tg_content, .toggle.alt .tg_content {
  display: initial !important;
}
```

I haven't tested this yet, but I reckon this should work for you.

**Comment by windowsrefund** [comment]
Thank you for the work-around. I'll certainly put it to good use but also wanted to share my thoughts on what you shared regarding layout. I do agree with everything you said in the case of a page being read for the first time. However, this logical line of thinking breaks down when it comes to subsequent reads of the information on a given page. In other words, wanting to get to a specific section of a given page is so common that any extra click (every page) just slows things down considerably. I'm all for minimalism but I'd encourage you to consider reversing the behavior so the TOC is shown by default but able to be hidden (by default) via a config option. Remember, it's not really "in the way" (like it would be if it were taking up space at the top of the page) since it's off to the side.

Thanks again.

**Comment by saschaleib** [comment]
Just as a little headsup to @windowsrefund: the latest version of the template now has an option for exactly this issue. Enjoy! :-)
