### ISSUE TITLE
Interaction with CodeMirror Font

### ISSUE THREAD

**Issue by Dob4115** [saschaleib/dokuwiki-template-ad-hominem#5]
I use CodeMirror as my editor and, for some reason, when I select ad-hominem, the font is not mono-spaced anymore. Switching back to Dokuwiki template fixes this, but I would like to use ad-hominem.

I tried switching the order of fonts in the template settings page, but nothing changed in CodeMirror.

**Comment by saschaleib** [comment]
Hello and thanks for the feedback. I have looked at CodeMirror, which I like very much, and I think will use myself in the future. 

The CodeMirror extension relies on elements that are underneath <pre> to inherit the font-family setting from this element. That is a bit problematic, as <pre> is not supposed to have child tags. So in the end, this would need to be fixed within CodeMirror. However, this plugin is not updated any longer, so it would be good to have a workaround...

I have now added monospace fonts settings to all child elements of <pre>, this will be available with the next release (which is planned in the coming days). This should fix this issue.

Be aware, however, that this may have other unintended consequences, so I consider this a "test" feature. If there are new issues appearing, I may roll this back...

If this happens (or if you can't wait for the update, you can also add one line to your user styles CSS (in the config folder). This line should be:

`main pre * { Consolas,Code,Courier New,Courier,monospace; }`

... or any other monospace font you are using.
