### ISSUE TITLE
PHP Error exceeded 30 seconds

### ISSUE THREAD

**Issue by Dob4115** [saschaleib/dokuwiki-template-ad-hominem#57]
I was editing a page and then it timed out. Here is the log data (I tried several times, so I may have several attempted saves here):

`
2024-12-09 11:42:10

E_WARNING: Trying to access array offset on value of type null
/volume1/web/dokuwiki/lib/plugins/structsection/syntax.php(89)
#0 /volume1/web/dokuwiki/lib/plugins/structsection/syntax.php(89): dokuwiki\ErrorHandler::errorHandler(2, 'Trying to acces...', '/volume1/web/do...', 89)
#1 /volume1/web/dokuwiki/inc/parser/renderer.php(126): syntax_plugin_structsection->render('metadata', Object(Doku_Renderer_metadata), Array)
#2 /volume1/web/dokuwiki/inc/parserutils.php(535): Doku_Renderer->plugin('structsection', Array, 5, '')
#3 /volume1/web/dokuwiki/inc/parserutils.php(299): p_render_metadata('sources:audio:b...', Array)
#4 /volume1/web/dokuwiki/lib/tpl/ad-hominem/rest/pageinfo.php(34): p_get_metadata('sources:audio:b...')
#5 {main}

2024-12-09 11:42:10

E_WARNING: Undefined array key 2
/volume1/web/dokuwiki/lib/tpl/ad-hominem/rest/pageinfo.php(72)
#0 /volume1/web/dokuwiki/lib/tpl/ad-hominem/rest/pageinfo.php(72): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/volume1/web/do...', 72)
#1 {main}

2024-12-09 11:42:10

E_WARNING: Undefined array key 2
/volume1/web/dokuwiki/lib/tpl/ad-hominem/rest/pageinfo.php(73)
#0 /volume1/web/dokuwiki/lib/tpl/ad-hominem/rest/pageinfo.php(73): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/volume1/web/do...', 73)
#1 {main}

2024-12-09 11:42:10

E_WARNING: Trying to access array offset on value of type null
/volume1/web/dokuwiki/lib/plugins/structsection/syntax.php(89)
#0 /volume1/web/dokuwiki/lib/plugins/structsection/syntax.php(89): dokuwiki\ErrorHandler::errorHandler(2, 'Trying to acces...', '/volume1/web/do...', 89)
#1 /volume1/web/dokuwiki/inc/parser/renderer.php(126): syntax_plugin_structsection->render('metadata', Object(Doku_Renderer_metadata), Array)
#2 /volume1/web/dokuwiki/inc/parserutils.php(535): Doku_Renderer->plugin('structsection', Array, 5, '')
#3 /volume1/web/dokuwiki/inc/parserutils.php(299): p_render_metadata('sources:audio:o...', Array)
#4 /volume1/web/dokuwiki/lib/tpl/ad-hominem/rest/pageinfo.php(34): p_get_metadata('sources:audio:o...')
#5 {main}

2024-12-09 11:42:10

E_WARNING: Undefined array key 2
/volume1/web/dokuwiki/lib/tpl/ad-hominem/rest/pageinfo.php(72)
#0 /volume1/web/dokuwiki/lib/tpl/ad-hominem/rest/pageinfo.php(72): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/volume1/web/do...', 72)
#1 {main}

2024-12-09 11:42:10

E_WARNING: Undefined array key 2
/volume1/web/dokuwiki/lib/tpl/ad-hominem/rest/pageinfo.php(73)
#0 /volume1/web/dokuwiki/lib/tpl/ad-hominem/rest/pageinfo.php(73): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/volume1/web/do...', 73)
#1 {main}

2024-12-09 11:42:17

E_ERROR: Maximum execution time of 30 seconds exceeded
/volume1/web/dokuwiki/inc/Parsing/Lexer/ParallelRegex.php(103)
#0 [internal function]: dokuwiki\ErrorHandler::fatalShutdown()
#1 {main}

2024-12-09 11:42:51

E_ERROR: Maximum execution time of 30 seconds exceeded
/volume1/web/dokuwiki/inc/Parsing/Lexer/ParallelRegex.php(103)
#0 [internal function]: dokuwiki\ErrorHandler::fatalShutdown()
#1 {main}

2024-12-09 11:43:05

E_WARNING: Undefined array key "_data"
/volume1/web/dokuwiki/lib/tpl/ad-hominem/my_template.php(235)
#0 /volume1/web/dokuwiki/lib/tpl/ad-hominem/my_template.php(235): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/volume1/web/do...', 235)
#1 [internal function]: _my_metaheaders_action(Array)
#2 /volume1/web/dokuwiki/inc/Extension/Event.php(134): call_user_func_array('_my_metaheaders...', Array)
#3 /volume1/web/dokuwiki/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger('_my_metaheaders...', true)
#4 /volume1/web/dokuwiki/lib/tpl/ad-hominem/my_template.php(215): dokuwiki\Extension\Event::createAndTrigger('TPL_METAHEADER_...', Array, '_my_metaheaders...', true)
#5 /volume1/web/dokuwiki/lib/tpl/ad-hominem/main.php(27): my_metaheaders()
#6 /volume1/web/dokuwiki/inc/actions.php(30): include('/volume1/web/do...')
#7 /volume1/web/dokuwiki/doku.php(131): act_dispatch()
#8 {main}

2024-12-09 11:43:05

E_WARNING: Undefined array key "_data"
/volume1/web/dokuwiki/lib/tpl/ad-hominem/my_template.php(240)
#0 /volume1/web/dokuwiki/lib/tpl/ad-hominem/my_template.php(240): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/volume1/web/do...', 240)
#1 [internal function]: _my_metaheaders_action(Array)
#2 /volume1/web/dokuwiki/inc/Extension/Event.php(134): call_user_func_array('_my_metaheaders...', Array)
#3 /volume1/web/dokuwiki/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger('_my_metaheaders...', true)
#4 /volume1/web/dokuwiki/lib/tpl/ad-hominem/my_template.php(215): dokuwiki\Extension\Event::createAndTrigger('TPL_METAHEADER_...', Array, '_my_metaheaders...', true)
#5 /volume1/web/dokuwiki/lib/tpl/ad-hominem/main.php(27): my_metaheaders()
#6 /volume1/web/dokuwiki/inc/actions.php(30): include('/volume1/web/do...')
#7 /volume1/web/dokuwiki/doku.php(131): act_dispatch()
#8 {main}

2024-12-09 11:43:18

E_WARNING: Trying to access array offset on value of type null
/volume1/web/dokuwiki/lib/plugins/structsection/syntax.php(89)
#0 /volume1/web/dokuwiki/lib/plugins/structsection/syntax.php(89): dokuwiki\ErrorHandler::errorHandler(2, 'Trying to acces...', '/volume1/web/do...', 89)
#1 /volume1/web/dokuwiki/inc/parser/renderer.php(126): syntax_plugin_structsection->render('metadata', Object(Doku_Renderer_metadata), Array)
#2 /volume1/web/dokuwiki/inc/parserutils.php(535): Doku_Renderer->plugin('structsection', Array, 5, '')
#3 /volume1/web/dokuwiki/inc/parserutils.php(299): p_render_metadata('biblestudy:devo...', Array)
#4 /volume1/web/dokuwiki/inc/common.php(262): p_get_metadata('biblestudy:devo...')
#5 /volume1/web/dokuwiki/doku.php(101): pageinfo()
#6 {main}

2024-12-09 11:43:50

E_ERROR: Maximum execution time of 30 seconds exceeded
/volume1/web/dokuwiki/inc/Parsing/Lexer/ParallelRegex.php(103)
#0 [internal function]: dokuwiki\ErrorHandler::fatalShutdown()
#1 {main}
`

Any idea where I can start looking through my markup to fix the problem?

**Comment by saschaleib** [comment]
Hello, it seems you have a problem with a regex somewhere, which seems to go into infinite regress. It is hard to say where it comes from, as the relevant parts (ie.e the ones with E_ERROR in them) all just refer to {main} as the source.

I would first disable all plugins to see if that helps – if it works after that, you may have to enable them one at a time to see which one causes the problems.

It is also possible that there is some really weird wikicode somewhere in the page. If the plugins weren't the cause, you can also try first saving the first half of the page, then the second half, and then try to drill it down to where the problem occurs. 

I would encourage you to also post the issue on the [DokuWiki Forum](https://forum.dokuwiki.org/), where somebody may have encountered a similar issue and can help you further.

For now, this doesn't look like an issue with the template to me

**Comment by Dob4115** [comment]
Sounds good, thanks for taking a look!

**Comment by Dob4115** [comment]
Incidentally, I did find a markup error. I had looked briefly before submitting the bug, but went back over it more thoroughly. I had a link like [[xxxxxxx|yyyyyyy] zzzzzz]].

**Comment by saschaleib** [comment]
Oh, that's interesting. You may want to report this back to the DokuWiki repository as well. This is clearly not legal markup, but it also shouldn't cause a regex timeout.
