### ISSUE TITLE
Editor left edge overlaps cursor

### ISSUE THREAD

**Issue by Dob4115** [saschaleib/dokuwiki-template-ad-hominem#6]
In the dokuwiki editor, when my cursor is on the left side, it is completely hidden by the edge of the editor box. This makes it hard to see cursor position (well, impossible, since it's hidden) especially when there are multiple blank lines together.

**Comment by saschaleib** [comment]
Hello again, could you give a bit more information, like what window size you are using, and which other extensions are installed. If possible, please post a screenshot...

Here's the editor for me, and while the cursor is very close to the edge, it is clearly visible for me:
![image](https://user-images.githubusercontent.com/961863/144703569-23158572-767c-4202-9ef6-c1a82633df1a.png)

**Comment by Dob4115** [comment]
Yes, that definitely looks better. I have the cursor on the third (blank) line:
![image](https://user-images.githubusercontent.com/49409988/144707356-b48795d4-9365-4861-9716-2789db688f9c.png)

I am in a desktop browser, but I have resized width all the way to minimum with no change in look. On my phone, I can see the cursor, more like the screenshot you have above. I use Vivaldi browser on both.

Here is a screenshot of my template settings, focusing on size:
![image](https://user-images.githubusercontent.com/49409988/144707478-a8e323e3-f986-4e4d-ac3a-e6a2183bf396.png)

**Comment by saschaleib** [comment]
OK, that looks like a bit of extra padding should do the trick... I have updated the files, will come with the next update. I just added a minimal extra space, let me know if it is not enough... I reckon we will need to find a good value by trial and error.
