### ISSUE TITLE
Back and Forward Links List?

### ISSUE THREAD

**Issue by Dob4115** [saschaleib/dokuwiki-template-ad-hominem#7]
Not an issue, more a general question: do you know of any way to make the "backlinks" page into more of a "links" page? Showing back and forward links in a list?

**Comment by saschaleib** [comment]
Hello and thanks for the request. I'm not sure if I understand it right: You mean, the "Links" page should show both, _incoming_ and _outgoing_ links for the page? Not sure if this can be done at template level, as this would be a functionality of the DokuWiki core, or maybe something that a plugin could do, but I'm a bit hesitant of moving plugin functionality into the template (though I have already reproduced the "cookielaw" plugin, but that should remain an exception...)

**Comment by Dob4115** [comment]
Yeah, no pressure. I was more asking because I hadn't seen anything else and I dont know where the interface lies between template and plugins.

I find looking at links helpful to get a sense of how i've understood the topic. Forward links get lost in the text.

**Comment by saschaleib** [comment]
Indeed, I'm afraid this is an issue that is pretty much out of scope for a template. It might be implemented as a plugin, or as an option in the DokuWiki core, but not a part of a template.
